FROM public.ecr.aws/lambda/python:3.11
RUN yum install -y gcc gcc-c++ cmake
COPY functions/processor/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY functions/classifier/handler.py ${LAMBDA_TASK_ROOT}/
CMD ["handler.handler"]