FROM public.ecr.aws/lambda/python:3.11
COPY functions/processor/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY functions/processor/handler.py ${LAMBDA_TASK_ROOT}/
CMD ["handler.handler"]